-- Supabase SQL Editor에서 실행: 모든 테이블 RLS 비활성화 (개발 단계)
ALTER TABLE "User" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Post" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Gallery" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Popup" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "History" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Setting" DISABLE ROW LEVEL SECURITY;

SELECT 'RLS disabled successfully!' AS result;
